Get rid of Preview because error with pod lint
- pod spec lint

 -> SwiftUtilityPodDemo (0.0.7)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  note: Target dependency graph (3 targets)
    - NOTE  | xcodebuild:  rosetta error: Failed to open libRosettaRuntime
    - ERROR | xcodebuild:  "output": "<unknown>:0: warning: compiler plugin not loaded: '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/usr\/bin\/swift-plugin-server; failed to initialize\n\/var\/folders\/dh\/m8w2rpbd26d9jcs302f5z4_h0000gp\/T\/CocoaPods-Lint-20240228-18339-pifmex-SwiftUtilityPodDemo\/Pods\/SwiftUtilityPodDemo\/SwiftUtilityPodDemo\/Views\/ErrorUtilView.swift:45:1: error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'\n#Preview {\n^\nSwiftUI.Preview:2:41: note: 'Preview(_:body:)' declared here\n@freestanding(declaration) public macro Preview(_ name: String? = nil, body: @escaping @MainActor () -> View) = #externalMacro(module: \"PreviewsMacros\", type: \"SwiftUIView\")\n                                        ^\n\/var\/folders\/dh\/m8w2rpbd26d9jcs302f5z4_h0000gp\/T\/CocoaPods-Lint-20240228-18339-pifmex-SwiftUtilityPodDemo\/Pods\/SwiftUtilityPodDemo\/SwiftUtilityPodDemo\/Views\/ThreeDotsLoadingView.swift:52:1: error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'\n#Preview {\n^\nSwiftUI.Preview:2:41: note: 'Preview(_:body:)' declared here\n@freestanding(declaration) public macro Preview(_ name: String? = nil, body: @escaping @MainActor () -> View) = #externalMacro(module: \"PreviewsMacros\", type: \"SwiftUIView\")\n                                        ^\n",